# services:
#   web:
#     build:
#       context: .
#     ports:
#       - 5173:5173
#     volumes:
#       - .:/app
#       - /app/node_modules

services:
  web:
    build:
      context: .
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true    # Enable polling for file changes
      - WATCHPACK_POLLING=true       # Enable webpack/vite file watching
    command: npm run dev -- --host   # Run in dev mode and allow external connections